# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b1432df9a20c57e97770492e52624d3f7a4ca6c17f54fe5a966eb0e368f44a090877c41e31b48e0151c8fa835d63e5cf14b31dafbef6b2dcd834311ab2396e

test:
  secret_key_base: f50b1ef533d62d20ab4400253ab4f5ce1c8b4b3f65445f5bfa246dde03182a867bfe21bdfc08aec18048449720aab5d6c7ae21e5d7c21971b6403b4832816d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
